import NavBar from "@/components/NavBar";
import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar>{children}</NavBar>
        </Providers>
      </body>
    </html>
  );
}
